repository:
  has_issues: true
  default_branch: main

branches:
  - name: main
    protection:
      required_status_checks:
        strict: true
        contexts: []
      enforce_admins: true
      required_pull_request_reviews:
        required_approving_review_count: 1
  - name: develop
    protection:
      required_status_checks:
        strict: true
        contexts: []
      enforce_admins: true
      required_pull_request_reviews:
        required_approving_review_count: 1
