name: Build Laravel 12 with Tenancy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout الكود
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Setup PHP 8.3 + Extensions
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, bcmath, pdo_mysql, xml, ctype, curl, json, openssl, tokenizer
          coverage: none

      # 3. Cache Composer
      - name: Cache Composer packages
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      # 4. Install Dependencies
      - name: Install Dependencies
        run: composer update --no-dev --optimize-autoloader

      # 5. Copy .env file
      - name: Copy .env
        run: cp .env.example .env

      # 6. Generate Laravel APP_KEY
      - name: Generate Key
        run: php artisan key:generate

      # 7. Publish Tenancy config & migrations
      - name: Publish Tenancy Config
        run: php artisan vendor:publish --tag=tenancy --force

      # 8. Run Laravel Migrations
      - name: Run Migrations
        run: php artisan migrate --force

      # 9. Optimize Laravel
      - name: Optimize Laravel
        run: php artisan optimize:clear

      # 10. Archive Build
      - name: Create Build Artifact
        run: zip -r build.zip . -x ".git/*" "tests/*" ".github/*" "storage/logs/*"

      # 11. Upload Artifact
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: laravel-build
          path: build.zip
